### PR TITLE
US120379 wizard component

### PR DESCRIPTION
**Pull request by JeremyWinkler**

### CODE REVIEW

**Comment by IhabAlkabary** [comment]
there is a bunch of linting issue

**Comment by JeremyWinkler** [comment]
> there is a bunch of linting issue

I dont think I updated my linter. I'll fix it.

**Review by lweber-d2l — DISMISSED** [review]
Looks good 👍

**Review by lweber-d2l — DISMISSED** [review]
Looks good

**Review by lweber-d2l — APPROVED** [review]

**Pull request merged**
