### PR TITLE
Fix 0 pages issue when log table is empty

### PR DESCRIPTION
**Pull request by lweber-d2l**
Ensure the number of pages shows 1 when there are 0 log entries.

### CODE REVIEW

**Comment by lweber-d2l** [comment]
This is best viewed with "Hide whitespace changes" checked.  I'm not sure why, but even though I changed one line, Github diff is convinced there is a whitespace change on every line.

**Review by Syeda-Azim — APPROVED** [review]

**Review by IhabAlkabary — DISMISSED** [review]

**Comment by IhabAlkabary** [comment]
> This is best viewed with "Hide whitespace changes" checked. I'm not sure why, but even though I changed one line, Github diff is convinced there is a whitespace change on every line.

I would check the end lines and see if there are being changed.

**Comment by IhabAlkabary** [comment]
One more file to fix regarding the line endings issue: `src/services/manageSchedulesDemoService.js`
Thanks for fixing this.

**Comment by lweber-d2l** [comment]
> One more file to fix regarding the line endings issue: `src/services/manageSchedulesDemoService.js`
> Thanks for fixing this.

Done - this file now has `LF` only for line endings.  This appeases the diff, but this file is now inconsistent with the other files.  We have a mix - some files are `LF` only, most are `CR LF` - we can discuss with the team.

**Comment by lweber-d2l** [comment]
This is what the UI looks like with this fix:
pagination-fixed-local-test

**Review by bamcdole — APPROVED** [review]

**Review by IhabAlkabary — APPROVED** [review]

**Pull request merged**
